# Generated by Django 5.1.4 on 2024-12-23 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_alter_customer_lead"),
        ("leads", "0002_remove_client_advertising_lead"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Client",
        ),
    ]
