# Generated by Django 5.1.4 on 2024-12-22 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotionchannel',
            options={'verbose_name': 'Канал продвижения', 'verbose_name_plural': 'Каналы продвижения'},
        ),
        migrations.AlterField(
            model_name='advertising',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='promotionchannel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
